Misc doc changes
elixir-ecto/tds pull request #123
Opened 2021-06-20 17:29 UTC by kianmeng

Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

2021-10-17 17:21 UTC, kianmeng commented
@josevalim Done. Please check, I'm assumed this project is maintained by Dashbit after ownership transfer?

2021-10-17 17:49 UTC, moogle19 requested changes

2021-10-17 17:49 UTC, moogle19 commented on lib/tds/binary_utils.ex
> +  A 16-bit signed integer.
This should be `A 32-bit signed integer.`.
The following documentation is also wrong. 
Would be nice if you could fix this.

2021-10-31 01:06 UTC, kianmeng commented on README.md
> +Copyright (c) 2021 Dashbit
> I am not sure if you should add Dashbit here. But I also have no idea about Copyright.

@josevalim Is `:tds` library under maintenance of `Dashbit` or someone else right now?

2021-10-31 06:11 UTC, josevalim commented on README.md
> +Copyright (c) 2021 Dashbit
It is not. Generally speaking, don’t change copyright lines, it is really up to maintainers. :)

2021-10-31 06:13 UTC, josevalim commented on README.md
> +Copyright (c) 2021 Dashbit
To be clear, @moogle19 is maintaining it right now and they can add their own copyright, but I believe he doesn’t have to either. :)

2021-11-06 06:54 UTC, kianmeng commented on README.md
> +Copyright (c) 2021 Dashbit
@josevalim Noted. Extra copyright line removed.
@moogle19 Please check again.

2021-12-23 12:45 UTC, kianmeng commented
@moogle19 Should I resolve the conflict and resubmit the PR again?

2021-12-31 11:17 UTC, moogle19 commented
@kianmeng 
Sorry for the late reply. Yes, that would be awesome!

2022-01-01 12:18 UTC, kianmeng commented
@moogle19 Done. Please check again.

2022-01-01 13:57 UTC, merged

2022-01-01 13:57 UTC, moogle19 commented
@kianmeng 
Thanks a lot!

2022-01-01 14:05 UTC, kianmeng commented
:+1: :tada: